language: python
cache: pip
dist: focal
env:
  - GIT_BRANCH=master
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install --upgrade coveralls urllib3 python-dateutil zipp cryptography pytest-runner
  - python setup.py install
# command to run tests
script:
  - python setup.py test
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then coveralls; fi
