#!/usr/bin/env python

import locale
import sys

from subprocess import PIPE, Popen

from n_utils import COMMAND_MAPPINGS, NDT_AND_CONSOLE, PATH_COMMANDS

SYS_ENCODING = locale.getpreferredencoding()
CONSOLE_PREFERRED = sorted([cmd.split("=")[0] for cmd in NDT_AND_CONSOLE])


def do_call(command):
    proc = Popen(command, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    output, err = proc.communicate()
    return (output + err).decode(SYS_ENCODING).strip().replace("'", "\\'")


def document_commands():
    print(
        "*This document is autogenerated by "
        "[https://github.com/NitorCreations/nameless-deploy-tools/blob/master/document_commands.py](document_commands.py). "  # noqa: E501
        "Do not edit by hand!*\n"
    )

    for command in sorted(COMMAND_MAPPINGS.keys()):
        if command in CONSOLE_PREFERRED:
            continue
        print(f"## `ndt {command}`\n")
        print("```bash")
        print(do_call(["ndt", command, "-h"]))
        print("```\n")

    for command in CONSOLE_PREFERRED:
        print(f"## `[ndt ]{command}`\n")
        print("```bash")
        print(do_call([command, "-h"]))
        print("```\n")

    for script in sorted(PATH_COMMANDS):
        name = script.split("/")[-1]
        print(f"## `{name}`\n")
        print("```bash")
        print(do_call([name, "-h"]))
        print("```\n")


if __name__ == "__main__":
    try:
        document_commands()
    except KeyboardInterrupt:
        # handle CTRL-C gracefully
        sys.exit("\ninterrupted")
