# Copyright 2016-2024 Nitor Creations Oy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resourceDeleteSnapshotsRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal: { Service: lambda.amazonaws.com }
          Action: sts:AssumeRole
    Path: /
    Policies:
      - PolicyName: deleteSnapshotsPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: ["ec2:DeleteSnapshot", "ec2:DescribeSnapshots"]
              Resource: ["*"]
            - Effect: Allow
              Action:
                [
                  "logs:CreateLogGroup",
                  "logs:CreateLogStream",
                  "logs:PutLogEvents",
                ]
              Resource: arn:aws:logs:*:*:*
resourceDeleteSnapshotsLambda:
  Type: AWS::Lambda::Function
  Properties:
    Code:
      ZipFile: { "Fn::ImportFile": delete-old-snapshots.min.js }
    Description: "Deletes snapshots older than a month that have a specific tag key/value"
    Handler: "index.handler"
    MemorySize: 128
    Runtime: nodejs4.3
    Timeout: 300
    Role: { "Fn::GetAtt": [resourceDeleteSnapshotsRole, Arn] }
