name: Python Black

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.py"
      - ".github/workflows/black.yml"
  pull_request:

# https://black.readthedocs.io/en/stable/integrations/github_actions.html
jobs:
  format:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Black format
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"
