name: Black

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - '**.py'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**.py'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: '**/*.py'

      - name: List all changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done

      - name: Set up Python environment
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Black
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"
          src: ${{ steps.changed-files.outputs.all_changed_files }}
