name: Python isort

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ruff.yml"
      - "**.py"
      - "requirements.txt"
      - "pyproject.toml"
  pull_request:
    paths:
      - ".github/workflows/ruff.yml"
      - "**.py"
      - "requirements.txt"
      - "pyproject.toml"

# https://github.com/marketplace/actions/python-isort
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: isort
        uses: isort/isort-action@v1.1.0
        with:
          requirementsFiles: "requirements.txt"
