name: isort

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.py"
  pull_request:

# https://github.com/marketplace/actions/python-isort
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: isort
        uses: isort/isort-action@v1.1.0
        with:
          requirementsFiles: "requirements.txt"
