name: Python Ruff

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.py"
      - ".github/workflows/ruff.yml"
  pull_request:

# https://github.com/chartboost/ruff-action
jobs:
  lint:
    runs-on: self-hosted
    name: ruff
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ruff
        uses: chartboost/ruff-action@v1
